// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCeuC2YdCSmPmNqdgmUKsNzMuIUtFi2b9E',
    appId: '1:90414726043:web:89c8f57181b3068af0bf3e',
    messagingSenderId: '90414726043',
    projectId: 'quickdeliveries',
    authDomain: 'quickdeliveries.firebaseapp.com',
    storageBucket: 'quickdeliveries.firebasestorage.app',
    measurementId: 'G-CJEPCYCDP8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDytBPC6WChJszl9_Mt0YhDhdGagBrkuBs',
    appId: '1:90414726043:android:78cb8413c4c6163ff0bf3e',
    messagingSenderId: '90414726043',
    projectId: 'quickdeliveries',
    storageBucket: 'quickdeliveries.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCruXFbmeJFxXr2eKdnkVmkr51Wop74K70',
    appId: '1:90414726043:ios:2ee7c312765f53a3f0bf3e',
    messagingSenderId: '90414726043',
    projectId: 'quickdeliveries',
    storageBucket: 'quickdeliveries.firebasestorage.app',
    iosBundleId: 'com.example.quickdeliveries',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCruXFbmeJFxXr2eKdnkVmkr51Wop74K70',
    appId: '1:90414726043:ios:2ee7c312765f53a3f0bf3e',
    messagingSenderId: '90414726043',
    projectId: 'quickdeliveries',
    storageBucket: 'quickdeliveries.firebasestorage.app',
    iosBundleId: 'com.example.quickdeliveries',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCeuC2YdCSmPmNqdgmUKsNzMuIUtFi2b9E',
    appId: '1:90414726043:web:c5d81dc19709a8b9f0bf3e',
    messagingSenderId: '90414726043',
    projectId: 'quickdeliveries',
    authDomain: 'quickdeliveries.firebaseapp.com',
    storageBucket: 'quickdeliveries.firebasestorage.app',
    measurementId: 'G-TR4JE14B53',
  );
}
